# Generated by Django 2.2.6 on 2019-10-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_lookbook', '0005_auto_20191007_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='look',
            name='look_id',
            field=models.IntegerField(unique=True, verbose_name='Lookbook id'),
        ),
    ]
