# Generated by Django 2.2.6 on 2019-10-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_lookbook', '0006_auto_20191007_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='look',
            name='unique_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
