# Generated by Django 2.2.6 on 2019-10-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_lookbook', '0007_look_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='look',
            name='unique_id',
        ),
    ]
