# Generated by Django 2.2.6 on 2019-10-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_lookbook', '0008_remove_look_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='look',
            name='look_id',
            field=models.IntegerField(verbose_name='Lookbook id'),
        ),
    ]
