# Generated by Django 2.2.6 on 2019-10-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icrawler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapyItem',
        ),
    ]
