# Generated by Django 2.2.6 on 2019-10-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icrawler', '0004_auto_20191007_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='look',
            name='look_id',
            field=models.IntegerField(verbose_name='Lookbook id'),
        ),
    ]
